service: hello-world-bs

provider:
  name: aws
  runtime: nodejs10.x
  profile: bookshlf
  region: us-east-2

functions:
  api:
    handler: server.server
    events:
      - http:
          path: / # this matches the base path
          method: ANY
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
